directory:
  - "."
framework:
  - "terraform"
compact: true
quiet: true          
soft-fail: false     
skip-check:
  - "CKV_AWS_144"    # Cross-Region Replication
  - "CKV_AWS_18"     # Access logging
  - "CKV2_AWS_62"    # Event notifications
  - "CKV2_AWS_61"    # Lifecycle configurations
  - "CKV_AWS_21"     # Versioning
  - "CKV_AWS_145"    # KMS Encryption (Allowing basic AES256 instead)

